### ISSUE TITLE
Occasional tokenOwnerAccountA not provided error.

### ISSUE THREAD

**Issue by gsfhhdstsr1323** [everlastingsong/solsandbox#1]
Hi! I'm using 08a_close_position.ts to withdraw liquidity from stSOL/SOL pool. Usually everything works fine, but sometimes I'm getting:  

ixAccounts.forEach((acc) => {
             ^
Error: Invalid arguments: tokenOwnerAccountA not provided.

Anyone else facing the same issue? Any help would be greatly appreciated.
Thank you very much :)

**Comment by everlastingsong** [comment]
Hi, anticode123 san !
I have committed fix as communicated in Discord.
Thanks for great feedback!
https://github.com/everlastingsong/solsandbox/commit/cdcab0119ac0a3c49741c808865acf6913a52384
